spring:
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "ru.otus.spring.model"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer