auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka1:9092,kafka2:9092,kafka3:9092
    metrics:
      port: 10030
      type: JMX
    name: Kafka
    properties: {}
    readOnly: false
rbac:
  roles: []
webclient: {}
